baseurl = "https://tmrtmhr.info/"
description = "個人ブログです。"
DefaultContentLanguage = "ja"
languageCode = "ja-JP"
theme = "castaway"
paginate = 10
googleAnalytics = "UA-92780964-1"
[params]
headerCover = "img/logo.jpg"

[taxonomies]
tag = "tags"

[languages]
[languages.ja]
title = "嵐の小舟より"
weight = 1

[languages.en]
title = "from the boat in the angry ocean"
