baseurl = "https://tmrtmhr.info/"
description = "ブログ"
languagecode = "ja-JP"
title = "嵐の小舟より"
theme = "castaway"
categories = [ "Game", "Tech" ]
paginate = 9
googleAnalytics = "UA-92780964-1"
[params]
headerCover = "img/logo.jpg"